### ISSUE TITLE
Problems with secgroup_ids combination

### ISSUE THREAD

**Issue by spech66** [eumel8/otc_ecs#7]
Hi @eumel8 
first let me thank you again for this very helpful roles. During our last session of creating new ECS I got some errors I didn't had before.

In the ecs module  (ecs/create and create_nic as well as secroup/lookup) there is this statement:

```
- name: Set fact for secgroup_ids if secgroup_id is defined
  set_fact:
    secgroup_ids: "{{ secgroup_ids }} + [ '{{ secgroup_id }}' ]"
    secgroup_names: "{{ secgroup_names }} + [ '{{ secgroup_name }}' ]"
  when:
    - secgroup_id is defined and secgroup_id| length != 0
```

If I run it I now get errors about wrong groups. However if I change this to this:

```
- name: Set fact for secgroup_ids if secgroup_id is defined
  set_fact:
    secgroup_ids: "[ '{{ secgroup_id }}' ]"
    secgroup_names: "[ '{{ secgroup_name }}' ]"
  when:
    - secgroup_id is defined and secgroup_id| length != 0
  ```

everything is working fine now. I didn't changed anything in our definitions. Do you have any ideas what I might missed here?

I tried both definitions
```
Definition
  otc_sg_default: "ansible-sg-default"
  ecs-xyz:
    secgroups: "ansible-sg-xyz"


Playbook
    # secgroups: "{{ vms[ecs_name].secgroups | default(default.otc_sg_default) }}"
    secgroup_name: "{{ vms[ecs_name].secgroups | default(default.otc_sg_default) }}"
```
